name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.1.1 [CE|EE|ECE 2.4.0-2.4.7] 21 Sep 2024
          tag_name: 1.1.1
          body: |2-
            ### softcommerce/module-core [1.5.4]
            - **Fix**: Cannot use "String" in namespace as it is reserved since PHP 7 [#13]

            ### softcommerce/module-freeagent-contact-profile [1.1.1]
            - **Compatibility**: Introduced compatibility with `softcommerce/module-profile` [#2]

            ### softcommerce/module-freeagent-creditmemo-profile [1.1.1]
            - **Compatibility**: Introduced compatibility with `softcommerce/module-profile` [#2]

            ### softcommerce/module-freeagent-invoice-profile [1.1.1]
            - **Compatibility**: Introduced compatibility with `softcommerce/module-profile` [#2]

            ### softcommerce/module-freeagent-profile [1.1.1]
            - **Compatibility**: Introduced compatibility with `softcommerce/module-profile` [#2]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
